baseURL = "http://escaperooms.nuevofoundation.org/nurassicpark"
languageCode = "en-us"
title = "Nurassic Park Times"
theme = "nurassicpark"
contentDir = "content/nurassicpark"
publishDir = "public/nurassicpark"

# settings from theme config.toml
# Copyright = "All rights reserved - 2021"

googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 6

#[[menu.main]]
  #name = "Home"
  #url = "/"

[author]
  name = "Nuevo Foundation"

[permalinks]
    post = "/post/:slug"

[params]
  description = "Welcome to Nurassic Park!"
  footer = "&copy; [Nuevo Foundation](https://www.nuevofoundation.org) 2021"
  author = "Nuevo Foundation"
  summary_length = 300

#[params.banner]
    #src = "images/nf_logo.png"

[params.text]
  back = "&larr; Back To Home"
  truncated = "&hellip;"
  edit = "Edit this page &rarr;" 

# this is to render raw html
[markup.goldmark.renderer]
unsafe= true
