baseURL = "http://example.org/"
languageCode = "en-us"
title = "Mission Control"
theme = "air"

[author]
  name = "Nuevo Foundation"

[permalinks]
    post = "/post/:slug"

[params]
  description = ""
  cover = "images/user.jpg"
  author = "Nuevo Foundation"
  # authorlocation = ""
  # authorwebsite = "https://syui.cf/hugo-theme-air"
  # bio= "my bio"
  logo = "images/nf_logo.png"
  # googleAnalyticsUserID = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  mainSections = ["post"]
  RSSLink = ""

[markup.goldmark.renderer]
    unsafe = true