baseURL = "http://escaperooms.nuevofoundation.org/outerspace"
LanguageCode= "en-US"
Title= "The Cyptic Cosmos 222"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2021"
canonifyurls = true

[author]
  name = "Nuevo Foundation"

[permalinks]
    post = "/post/:slug"

[params]
  # cover = "images/user.jpg"
  author = "syui"
  authorlocation = ""
  # authorwebsite = "https://syui.cf/hugo-theme-air"
  # bio= "my bio"
  logo = "images/nf_logo.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  # githubName = "syui"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  mainSections = ["post"]

# this is to render raw html
[markup.goldmark.renderer]
unsafe= true
